### ISSUE TITLE
Orechid not displaying as disabled

### ISSUE THREAD

**Issue by WintersFrost** [DragonTechMC/Modpack-Issues#10]
Modpack: Dragon Industries

Modpack Type: Technic

Issue Description: The orechid and orechid ignem both have the recipes disabled, however in JEI it doesn't diasplay the items as being disabled.

Related Files:

https://gyazo.com/dddee053096327259b6a3da3ec32d950

**Comment by yepidoodles** [comment]
Will be fixed when I update the clients today.
