### ISSUE TITLE
Awakened Damage Value

### ISSUE THREAD

**Issue by WintersFrost** [DragonTechMC/Modpack-Issues#11]
Modpack: Dragon Industries

Modpack Type: Technic

Issue Description: The awakened pipe piece states that the damage level for a laser should be 35, however this is not the case. Shown below is an example of what it says and there is also a screenshot of a fully awakened laser gun which displays the damage value as being 3.5 (my theory is that it's a typo as all other weapons that are awakened have the damage value of 35)

Related Files:
Example Image:
https://gyazo.com/96290109d5ea89edff628524459e4d2c
Screenshot of Laser gun:
https://gyazo.com/058731f2b4b7d54e0204a849439a8e3d

**Comment by yepidoodles** [comment]
See https://github.com/Landmaster/PlusTiC/issues/206#issuecomment-416007244
