### ISSUE TITLE
Core Sample Drill recipe 

### ISSUE THREAD

**Issue by WintersFrost** [DragonTechMC/Modpack-Issues#15]
Modpack: Dragon Industries

Modpack Type:Technic

Issue Description: The recipe for the core sample drill needs to be disabled and the item needs to have the disabled tag, so players don't try to make the excavator.

Related Files:

https://gyazo.com/141576d33ccef439ad63e7efac89af65

**Comment by yepidoodles** [comment]
Was already fixed, just needs a pack update.
