### ISSUE TITLE
failed to load avatar

### ISSUE THREAD

**Issue by ghost** [DragonTechMC/Modpack-Issues#17]
Modpack: [Dragon Industries]  

Modpack Type: [Technic]

[Issue Description - Include what mods/ plugins you think are responsible and steps to reproduce if applicable]

[B#360] Download of https://crafatar.com/avatars/yepidoodles?size=60&helm Failed!
[B#360] Error downloading user avatar: yepidoodles

Error shown on url: Invalid UUID

Open Technic Launcher + Debug Console + Open Dragon Industries Modpack (dont launch it)

FIX: replace the old url with: https://crafatar.com/avatars/e9c24ac2-427f-45bf-bdb3-1b6e7950b09c?size=60&helm     

//crafatar uses uuid instead of username now.

Related Files:

[Crash reports, logs, screenshots - Please use gist.github.com or pastebin.com to post reports and logs]

Extra info:

[Modifications to your client - Change in mods/ texture packs/ shaders, etc. And anything else you want to add]

**Comment by yepidoodles** [comment]
This is to do with the Technic, and nothing to do with us.
