### ISSUE TITLE
Draconic Sword upgrade recipes issue

### ISSUE THREAD

**Issue by NashArnot** [DragonTechMC/Modpack-Issues#18]
Modpack: Dragon Industries

Modpack Type: Technic

the recipe for both draconic attack upgrade and attack Aoe upgrade have broken recipes, showing in Jei needing a gold sword and diamond sword.
In place of the gold sword is the ender (ender io), but is ment for the diamond sword replacement(said by one of the staff) and the diamond sword replacement is unknown. 

Related Files:

none

Extra info:

none

**Comment by yepidoodles** [comment]
Sorry I didn't see this issue before now,

The current recipes are as follows:

```
// Upgrade Key (Attack Damage)
recipes.removeShaped(<draconicevolution:tool_upgrade:3>);
recipes.addShaped(<draconicevolution:tool_upgrade:3>,
				[[<minecraft:dye:4>,<draconicevolution:draconic_core>,<minecraft:dye:4>],
				[<ore:ingotDraconium>,<enderio:item_dark_steel_sword>,<ore:ingotDraconium>],
				[<minecraft:dye:4>,<draconicevolution:draconic_core>,<minecraft:dye:4>]]);
                
// Upgrade Key (Attack AOE)
recipes.removeShaped(<draconicevolution:tool_upgrade:4>);
recipes.addShaped(<draconicevolution:tool_upgrade:4>,
				[[<minecraft:dye:4>,<draconicevolution:draconic_core>,<minecraft:dye:4>],
				[<ore:ingotDraconium>,<enderio:item_end_steel_sword>,<ore:ingotDraconium>],
				[<minecraft:dye:4>,<draconicevolution:draconic_core>,<minecraft:dye:4>]]);
```

As you can see, the swords are replaced as you say, but as these scripts are not on your client yet, they will appear as not working until you click on the output, but it will make them. You can add these manually by going into your modpack folder, going into scripts and then opening `DraconicEvolution.zs` in a file editor (right click and click edit), and pasting it in, then restarting your game.

They'll be added next time I update, let me know if you have any further problems.

~ Alice
