### ISSUE TITLE
Optifine not included

### ISSUE THREAD

**Issue by WintersFrost** [DragonTechMC/Modpack-Issues#19]
Modpack: Dragon Industries

Modpack Type: Technic

Issue Description: Apparently optifine doesn't come pre-installed with Dragon Industries, a streamer pointed this out. Asked two admins who said it should be included.

**Comment by WintersFrost** [comment]
To note, I think the friend was using the twitch/ curse version

**Comment by yepidoodles** [comment]
It doesn't come included in the Twitch/ Curse version as Optifine isn't available on Curseforge. Curseforge rejects the modpack if I try to add it manually, so if anyone uses the Twitch version and wants Optifine, they'll need to add it to their clients themselves, unfortunately.
