### ISSUE TITLE
Shuriken From Tinker's Mod

### ISSUE THREAD

**Issue by komikQ** [DragonTechMC/Modpack-Issues#2]
## Everlands

Shuriken from Tinker's Construct mod is not working inside a claimed land. 

### Related Files

(in Claims)

The ammo is full :
https://gyazo.com/d27781253a25e684bf29cf20a587dd36
Shooting it, which is nothing happens :
https://gyazo.com/30e229e801cf604a7f642125a57354bc
proof the ammo used :
https://gyazo.com/bdca3e35fe0d357ae9a9c4e8c33eb4dc

### Extra info

normal install, no shaders or texture pack.

**Comment by yepidoodles** [comment]
I may have fixed this but it will need testing by a normal player.
