### ISSUE TITLE
Di: Rod Of Terra Firma from Botania not working...

### ISSUE THREAD

**Issue by MatthewFMMS** [DragonTechMC/Modpack-Issues#6]
Modpack: Dragon Industries

Modpack Type: Technic

Issue Description -The Botania Rod of Terra Firma Doesn't work. I deleted the custom main menu and added World edit, The replay mod, and schematics.

Related Files:

none

Extra info:

The effects for the rod worked outside my personal claim but did nothing and did not use mana. It didn't do anything in my claim.

**Comment by yepidoodles** [comment]
It looks like it's a Sponge related issue as the Rod works fine on Single player. It should have been banned/ disabled anyway, so that will be in effect on the restart.
