### ISSUE TITLE
ME Drive

### ISSUE THREAD

**Issue by WintersFrost** [DragonTechMC/Modpack-Issues#9]
Modpack: Dragon Industries

Modpack Type: Technic

Issue Description: The ME drive from applied energistics 2 can be crafted with the old recipe. (recipe needs to be disabled)

Related Files:

https://gyazo.com/36830e7b7fe1ce6d5f0f9583efee0e6d

Extra info:

Forgot to get a screenshot before I crafted it, you can see in the screenshot above that it was crafted though.

**Comment by yepidoodles** [comment]
Client will be updated with fix tomorrow.
